### ISSUE TITLE
datasources and posdatasources

### ISSUE THREAD

**Issue by mbredif** [LI3DS/pg_li3ds#10]
why are datasources and posdatasources separated ?
the version id in the postdatasources seems redundant with the fact that a postdatasource provides a trajectory which is used to create a transfo, that will be integrated into a transfo tree and, in turn, a platform config.
This should get more clear as this part of the project gets implemented.

**Comment by mbredif** [comment]
Another difference is that a datasource references a referential, whereas a posdatasource references a sensor. I think both should reference a referential.

**Comment by elemoine** [comment]
It was decided in recent discussions that we are going to remove posdatasource and use datsource for trajectories as well.

@mbredif @ldgeo can you please confirm?

**Comment by mbredif** [comment]
I agree. I suggest to use datasources exclusively for now and see if that raises an issue. If not, we will remove posdatasources.

**Comment by elemoine** [comment]
> I agree. I suggest to use datasources exclusively for now and see if that raises an issue. If not, we will remove posdatasources.

I started to work on branches that remove it.
