### ISSUE TITLE
transfo_tree.isdefault -> platform_config.isdefault

### ISSUE THREAD

**Issue by mbredif** [LI3DS/pg_li3ds#4]
I propose to switch the isdefault attribute from  transfo_tree to platform_config.
I see the platform_config as an equivalent to a commit in git : it offers a consistent view of the calibration of a platform (including trajectories, internal and external calibrations). Then the isdefault attribute on the platform_config would be similar to the commit on the master branch.
I am not sure to see value in transfo_tree.isdefault as the proposed approach to create a config would be to either start from scratch and provide transfo_trees for all sensors or to modify partially an existing config.

**Comment by elemoine** [comment]
For now we said that we're just going to remove `transfo_tree.isdefault` w/o actually moving it to `platform_config` for now.

**Comment by mbredif** [comment]
Ok to remove it and eventually add it back when it will be clearer where it belongs (if required)
