### ISSUE TITLE
sensor_connections boolean default false -> sensor int references sensor(id) default null

### ISSUE THREAD

**Issue by mbredif** [LI3DS/pg_li3ds#5]
It is currently convoluted to retrieve the `sensor` of a `transfo_tree` that is not a `sensor_connection`.
I propose to have instead a `sensor` field which would be : 
- null when `sensor_connections` was true
- the id of the common sensor of the referentials linked by the transfos of the transfo_tree if it was false.

**Comment by elemoine** [comment]
How do you determine the "common" sensor? Is it the one associated with the source referential of the first transfo in the transfo tree?

```sql
SELECT r.sensor as sensor_id
FROM li3ds.transfo_tree tt
JOIN li3ds.transfo t on t.id == tt.transfos[1]
JOIN li3ds.referential r on r.id = t.source
WHERE tt.id = 1;
```

**Comment by mbredif** [comment]
To rephrase my proposal : If all sources and targets of all transfos of the transfo_tree agree on a common sensor, then this is the sensor of the transfo_tree, otherwise, set it to null.

**Comment by elemoine** [comment]
Ok so not necessarily the source of the the first transfo.

What about the case where the transfo tree is a chain of transfos? Is there a "common sensor" in that case?

**Comment by mbredif** [comment]
It depends whether its a transfo tree linking referentials of a single sensor or one that links referentials of multiple sensors.
