### ISSUE TITLE
jsonb schema validation

### ISSUE THREAD

**Issue by mbredif** [LI3DS/pg_li3ds#7]
as a followup to #6, jsonb attributes in sensors and transfos could be checked against a JSON schema.
https://github.com/gavinwahl/postgres-json-schema could maybe fit the bill : 

```
ALTER TABLE sensor ADD CONSTRAINT sensor_spec_is_valid CHECK 
(validate_json_schema(schema, specifications));
```

A difficulty could be that the schema is not part of the sensor/transfo tables but of the sensor_type/transfo_type tables, referenced by a type attribute.

**Comment by elemoine** [comment]
We already have a `check_transfo_args` constraint on the `transfo.parameters` column. It just checks that the `parameters` JSON object has the expected keys. Are you suggesting to be more strict on the constraint?

> A difficulty could be that the schema is not part of the sensor/transfo tables but of the sensor_type/transfo_type tables, referenced by a type attribute.

Right, I guess we'd need to use `validate_json_schema` in our own constraint function.

**Comment by elemoine** [comment]
Let's close this for now. @mbredif feel free to re-open if you think we should work on that.

**Comment by mbredif** [comment]
ok
