### ISSUE TITLE
"Sensor group" is not intuitive

### ISSUE THREAD

**Issue by mbredif** [LI3DS/pg_li3ds#8]
The fact that a sensor group does currently only mean a group of referential that are not part of a sensor is kind of misleading.

**Comment by elemoine** [comment]
As I understand it, a sensor group is a sensor whose type is "group". The sensor group is associated to a (base) referential, itself linked to other referentials through transformations. These other referentials are themselves associated to sensors, which are the sensor group's sub-sensors (e.g. the cameras on a structure). So if my understanding is correct, the data model sounds ok to me.

**Comment by mbredif** [comment]
Actually, the referentials of a sensor group are currently referencing the sensor group itself and there is no notion of sub-sensors. Sensors (group or not) are linked together with an (identity) transform linking one referential from one sensor to a referential of the other.

**Comment by elemoine** [comment]
> Actually, the referentials of a sensor group are currently referencing the sensor group

You mean both the base referentials and the other referentials should be linked to the sensor group itself?

> and there is no notion of sub-sensors

I know there is no notion of sub-sensors in the data model. By sub-sensors I meant the cameras on a structure. Like we have in https://github.com/LI3DS/micmac_li3ds/blob/master/data/blinis_20161205.xml.

**Comment by elemoine** [comment]
Take the diagram at the end of the [micmac_li3ds README](https://github.com/LI3DS/micmac_li3ds). The `026`, `025`, `024` and `023` boxes are referentials. What sensors are these referentials linked to? The group sensor? Again, my understanding was that they were linked to the camera sensors, i.e. those corresponding to the `AutoCal_Foc-12000_Cam-Caml02X_20161205a.xml` files in the [micmac_li3ds data directory](https://github.com/LI3DS/micmac_li3ds/tree/master/data).

**Comment by mbredif** [comment]
Referentials like `023` are related to the sensor group of the blini.
The calib xml will create an external euclidean referentials for the camera.
Then a transfo_tree with sensor_connection=True will include a transform that will link these 2 referentials with an identity transform to document that which camera is positionned at position `023`.

**Comment by elemoine** [comment]
As discussed, let's close this for now.
