### ISSUE TITLE
sensor.root semantics ?

### ISSUE THREAD

**Issue by mbredif** [LI3DS/pg_li3ds#9]
The notion of the sensor.root is not clear : any node could be the root of a transfo tree referencing it...
What is needed from my perspective is the ability to get, given a sensor, its default referential for new datasets when a datasource is created (to fill in its `referential` field). 

A possibility would be to rename `root` as something more explicit that this means it is the default referential for creating datasources from this referential's sensor.
Another would be to move this to the sensor, having there a reference to its default referential (with the issue of a circular foreign key referencing between sensors and referentials).

**Comment by elemoine** [comment]
It was decided in recent discussions that we're going to remove the `root` field in `referential`. @mbredif, @ldgeo, agree?

**Comment by mbredif** [comment]
agreed

**Comment by elemoine** [comment]
See https://github.com/LI3DS/api-li3ds/commit/eb91bb43ac942923f807e1215f6aabbca42f48b3 for the changes implied on the API side.

There is one remaining reference to `referential.root`: https://github.com/LI3DS/api-li3ds/blob/master/api_li3ds/apis/itowns.py#L111. I am not sure about this one. @ldgeo @mbredif what do you think? Do we really need `r.root` here?

**Comment by mbredif** [comment]
You can safely remove the `and r.root` filter.
